[package]
name = "rusty_gif"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
image = "0.24.7"
indicatif = "0.17.7"
rayon = "1.8.0"
